name: AriKeysRedux
version: '${version}'
main: org.nerfoscar.arikeysredux.AriKeysReduxMain
api-version: '1.20'
authors: [ASangarin, NerfOscar]
description: A fork of the plugin and mod which can send custom key presses to a spigot server
softdepend: [ PlaceholderAPI, MythicMobs ]
commands:
  arikeysredux:
    description: The main command for AriKeysRedux.
    aliases: [ "akr" ]
    permission: arikeysredux.admin
    usage: "Usage: /arikeysredux [reload|info]"
permissions:
  arikeysredux.admin:
    description: The main permission for AriKeys.
    default: op