modLoader = "javafml"
loaderVersion = "[43,)"
issueTrackerURL = "https://github.com/NerfOscar/AriKeys-Redux/issues"
license = "MIT"

[[mods]]
modId = "arikeysredux"
version = "${version}"
displayName = "AriKeysRedux"
authors = "ASangarin, NerfOscar"
description = '''
Allows the Minecraft client to send AriKeyRedux keypresses to the server.
'''
logoFile = "icon.png"

[[dependencies.arikeysredux]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.arikeysredux]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.4,)"
ordering = "NONE"
side = "CLIENT"